version: "3.3"

# MINIO Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-01-01T16-36-33Z
  # command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  command: server --console-address ":9001" http://minio{1...2}/data{1...2}
  expose:
    - "9000"
    - "9001"
  # environment:
    # MINIO_ROOT_USER: minioadmin
    # MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

services:
  # MinIO service definitions
  # starts 4 docker containers running minio server instances.
  # using nginx reverse proxy, load balancing, you can access
  # it through port 9000.
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - ./minio/data/data1-1:/data1
      - ./minio/data/data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - ./minio/data/data2-1:/data1
      - ./minio/data/data2-2:/data2

  # minio3:
  #   <<: *minio-common
  #   hostname: minio3
  #   volumes:
  #     - ./minio/data/data3-1:/data1
  #     - ./minio/data/data3-2:/data2

  # minio4:
  #   <<: *minio-common
  #   hostname: minio4
  #   volumes:
  #     - ./minio/data/data4-1:/data1
  #     - ./minio/data/data4-2:/data2

  web:
    container_name: web
    restart: unless-stopped
    build: 
      context: .
      dockerfile: ./docker/shared/web.dockerfile
    volumes:
      - ./web:/app
    env_file:
      - .env
    expose:
      - "5173"

  database:
    container_name: database
    hostname: database
    restart: unless-stopped
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --allow-guests
      - --auth
      - --log
      - $DB_LOG_LEVEL
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - file:/db
    volumes:
      - ./db/data:/db
    image: surrealdb/surrealdb:v1.0.2
    expose:
      - "8000"

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
      - "8000:8000"
      - "5173:5173"
    depends_on:
      - minio1
      - minio2
      - web
      - database
      # - minio3
      # - minio4